// Fill out your copyright notice in the Description page of Project Settings.


#include "Base/CharacterBase.h"
#include "ActionBase.h"
#include "ActionComponent.h"
#include "DA/ActionLoadOutDA.h"
#include "Router/ActionRouter.h"
#include "CharacterActionStatComponent.h"
#include "EnhancedInputComponent.h"
#include "Camera/CameraComponent.h"
#include "Component/InputProxyComponent.h"
#include "Components/CapsuleComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "Router/CMoveRouter.h"
#include "InfinityFightersGameModeBase.h"
#include "Component/CBrainComponent.h"

#include "EnhancedInputComponent.h"
#include "Blueprint/UserWidget.h"
#include "Component/CBrainComponent.h"
#include "Component/InputProxyComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Components/WidgetComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "UObject/ConstructorHelpers.h"
#include "Engine/StaticMesh.h"
#include "BattleManager.h"
#include "NiagaraComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Animation/AnimInstance.h"
#include "Animation/AnimMontage.h"
#include "Components/SphereComponent.h"

// Sets default values
ACharacterBase::ACharacterBase()
{
	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	ActionRouter = CreateDefaultSubobject<UActionRouter>(TEXT("ActionRouter"));
	ActionComponent = CreateDefaultSubobject<UActionComponent>(TEXT("ActionComp"));
	ActionStatComp = CreateDefaultSubobject<UCharacterActionStatComponent>(TEXT("ActionStatComp"));
	_SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	_SpringArm->SetupAttachment(GetCapsuleComponent());
	_SpringArm->SetRelativeLocation(FVector(0, 0, 0));
	Camera = CreateDefaultSubobject<UCameraComponent>(TEXT("CamComp"));
    Camera->SetupAttachment(_SpringArm);
    FlyingObject = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("FlyingObject"));
    if (FlyingObject)
    {
        FlyingObject->SetupAttachment(GetMesh());
        FlyingObject->SetRelativeLocation(FVector(0.f, 0.f, 0.f));
        FlyingObject->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        FlyingObject->SetVisibility(false, true);
        static ConstructorHelpers::FObjectFinder<UStaticMesh> SphereMesh(TEXT("/Engine/BasicShapes/Sphere.Sphere"));
        if (SphereMesh.Succeeded())
        {
            FlyingObject->SetStaticMesh(SphereMesh.Object);
            FlyingObject->SetWorldScale3D(FVector(0.5f));
        }
    }

	

	_SpringArm->bUsePawnControlRotation = true; // м»ЁнҠёлЎӨлҹ¬ нҡҢм „мқ„ мҠӨн”„л§Ғм•”мқҙ л”°лҰ„(нҠ№нһҲ Pitch)
	_SpringArm->bInheritPitch = true;           // м•Ҳм „л№ө (ліҙнҶө кё°ліёк°’ trueм§Җл§Ң нҳ№мӢң лӘЁлҘҙлӢҲ)
	_SpringArm->bInheritYaw   = true;
	_SpringArm->bInheritRoll  = true;

	// м№ҙл©”лқјлҠ” мҠӨн”„л§Ғм•”мқҳ нҡҢм „мқ„ к·ёлҢҖлЎң мӮ¬мҡ©
	Camera->bUsePawnControlRotation = false;

	InputProxy = CreateDefaultSubobject<UInputProxyComponent>(TEXT("InputProxy"));
	Brain      = CreateDefaultSubobject<UCBrainComponent>(TEXT("Brain"));
	MoveRouter = CreateDefaultSubobject<UCMoveRouter>(TEXT("MoveRouter"));

	// AimEnemy мң„м Ҝ м»ҙнҸ¬л„ҢнҠё мғқм„ұ
	AimEnemyWidget = CreateDefaultSubobject<UWidgetComponent>(TEXT("AimEnemyWidget"));
	AimEnemyWidget->SetupAttachment(GetMesh());
	AimEnemyWidget->SetRelativeLocation(FVector(0.0f, 0.0f, 100.0f)); // мәҗлҰӯн„° лЁёлҰ¬ мң„
	AimEnemyWidget->SetWorldScale3D(FVector(0.3f)); // мҡ”мІӯлҗң мҠӨмјҖмқј
	AimEnemyWidget->SetWidgetSpace(EWidgetSpace::Screen); // н•ӯмғҒ нҷ”л©ҙмқ„ н–Ҙн•ҳлҸ„лЎқ
	AimEnemyWidget->SetVisibility(false); // кё°ліём ҒмңјлЎң мҲЁк№Җ

	// UI - м—¬лҹ¬ кІҪлЎң мӢңлҸ„
	static ConstructorHelpers::FClassFinder<UUserWidget> tempCrosshair(TEXT("'/Game/UI/Aim/WBP_Aim.WBP_Aim_C'"));
	if (tempCrosshair.Succeeded())
	{
		crosshairUIFactory = tempCrosshair.Class;
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("WBP_Aim_C мң„м Ҝ нҒҙлһҳмҠӨ лЎңл“ң мӢӨнҢЁ: WBP_Aim_C"));
	}

	// BP_AimEnemy мң„м Ҝ нҒҙлһҳмҠӨ м„Өм •
	static ConstructorHelpers::FClassFinder<UUserWidget> AimEnemyWidgetFinder(TEXT("/UI/Aim/BP_AimEnemy.BP_AimEnemy_C"));
	if (AimEnemyWidgetFinder.Succeeded())
	{
		AimEnemyWidgetClass = AimEnemyWidgetFinder.Class;
		UE_LOG(LogTemp, Log, TEXT("BP_AimEnemy мң„м Ҝ нҒҙлһҳмҠӨ лЎңл“ң м„ұкіө"));
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("BP_AimEnemy мң„м Ҝ нҒҙлһҳмҠӨ лЎңл“ң мӢӨнҢЁ: BP_AimEnemy"));
	}

	bUseControllerRotationPitch = false;   // л©”мӢң/нҸ°мқҖ Pitch мҳҒн–Ҙ X
	bUseControllerRotationYaw   = true;
	bUseControllerRotationRoll  = false;

	if (auto* M = GetCharacterMovement())
	{
		M->bOrientRotationToMovement   = false;
		M->bUseControllerDesiredRotation = true;
	}

	// м№ҙл©”лқј м„ёнҢ…
	_SpringArm->bUsePawnControlRotation = true;  // м№ҙл©”лқјл§Ң м»ЁнҠёлЎӨлҹ¬ PitchлҘј л”°лқјк°җ
	Camera->bUsePawnControlRotation     = false;

	// н”„л Ҳмқҙл°Қ(м—җмһ„ мӨ‘м•ҷ, мәҗлҰӯн„° м•„лһҳ)
	_SpringArm->SetRelativeLocation(FVector(0, 0, 30)); // н”јлІ— мЎ°кёҲ лӮ®м¶”кі 
	_SpringArm->TargetOffset      = FVector(0, 0, 50);  // ліҙлҠ” м§Җм җмқ„ мң„лЎң
	_SpringArm->TargetArmLength   = 380.f;              // кұ°лҰ¬
	Camera->SetFieldOfView(80.f);

	_SpringArm->bDoCollisionTest = true; // мң м§Җ
	_SpringArm->ProbeSize        = 6.f;  // кё°ліё 12 вҶ’ мӨ„мқҙл©ҙ кіјлҜј л°ҳмқ‘ мҷ„нҷ”
	_SpringArm->CameraLagSpeed   = 12.f; // л¶Җл“ңлҹҪкІҢ
	_SpringArm->bEnableCameraLag = true;

	//лҰ¬мҠӨнҸ°мҡ©лІ„лё”
	RespawnProtectionSphere = CreateDefaultSubobject<USphereComponent>(TEXT("RespawnProtectionSphere"));
	if (RespawnProtectionSphere)
	{
		RespawnProtectionSphere->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		RespawnProtectionSphere->SetVisibility(false); // кё°ліём ҒмңјлЎң мҲЁк№Җ
	}

}

// Called when the game starts or when spawned
void ACharacterBase::BeginPlay()
{
	Super::BeginPlay();


	InitActionRouterMapFromDa();
	InitActionsFromLoadout(); // мәҗлҰӯн„°к°Җ мҶҢмң н•ҳлҠ” м•Ўм…ҳл“Өмқ„ мјҖлҰӯн„°лІ мқҙмҠӨм—җ л“ұлЎқ
	InitStatsFromDA(); //лҠҘл Ҙм№ҳ кҙҖл Ё м •ліҙл“Өмқ„ DAлҘј мқҙмҡ©н•ҳм—¬ мҙҲкё°нҷ”

	// AI мәҗлҰӯн„°мқё кІҪмҡ° мӢңм•јк°Ғ мІҙнҒ¬ нғҖмқҙлЁё мӢңмһ‘
	if (Brain && Brain->Mode == EBrainMode::AI)
	{
		// AimEnemy мң„м Ҝ м„Өм •
		SetupAimEnemyWidget();
		
		// мҙҲкё°м—җлҠ” мң„м Ҝ мҲЁк№Җ
		ShowAimEnemyWidget(false);

		// мЈјкё°м ҒмңјлЎң н”Ңл Ҳмқҙм–ҙ мӢңм•јк°Ғ мІҙнҒ¬
		GetWorldTimerManager().SetTimer(WidgetUpdateTimerHandle, this,
			&ACharacterBase::UpdateAimEnemyWidgetVisibility, UpdateFrequency, true);

		UE_LOG(LogTemp, Log, TEXT("AI мәҗлҰӯн„°мқҳ мӢңм•јк°Ғ мІҙнҒ¬ мӢңмһ‘: %s"), *GetName());
	}

	if (ActionStatComp)
	{
		ActionStatComp->OnDeath.AddDynamic(this, &ACharacterBase::HandleDeath);
	}

	if (APlayerController* PC = Cast<APlayerController>(GetController()))
	{
		if (PC->PlayerCameraManager)
		{
			PC->PlayerCameraManager->ViewPitchMin = -10.f; //-80
			PC->PlayerCameraManager->ViewPitchMax =  25.f; //80
		}
	}

	// UI мғқм„ұмқ„ м•Ҫк°„ м§Җм—°мӢңмјң PlayerController мӨҖл№„ мҷ„лЈҢ лҢҖкё°
	FTimerHandle UITimerHandle;
	GetWorld()->GetTimerManager().SetTimer(UITimerHandle, [this]()
	{
		if (APlayerController* PC = Cast<APlayerController>(GetController()))
		{
			
			if (crosshairUIFactory)
			{
				FName CurrentLevel = FName(*UGameplayStatics::GetCurrentLevelName(GetWorld()));
				if (CurrentLevel == "INGAME_MAP")
				{
					crosshairUI = CreateWidget<UUserWidget>(PC, crosshairUIFactory); 
					if (crosshairUI != nullptr)
					{
						crosshairUI->AddToViewport(1000); // лҶ’мқҖ Z-OrderлЎң м„Өм •
						crosshairUI->SetVisibility(ESlateVisibility::Visible);
						UE_LOG(LogTemp, Warning, TEXT("BP_Aim UI нҷ”л©ҙ м¶”к°Җ м„ұкіө!"));
					}
					else
					{
						UE_LOG(LogTemp, Error, TEXT("CreateWidget мӢӨнҢЁ"));
					}
				}
			}
			else
			{
				// лҹ°нғҖмһ„м—җм„ң лё”лЈЁн”„лҰ°нҠё нҒҙлһҳмҠӨ лЎңл”© мӢңлҸ„
				UClass* FoundClass = LoadClass<UUserWidget>(nullptr, TEXT("/UI/Aim/BP_Aim.BP_Aim_C"));
				if (!FoundClass)
				{
					FoundClass = LoadClass<UUserWidget>(nullptr, TEXT("/UI/Aim/BP_Aim.BP_Aim_C"));
				}
				if (!FoundClass)
				{
					FoundClass = LoadClass<UUserWidget>(nullptr, TEXT("/UI/Aim/BP_Aim.BP_Aim_C"));
				}
				
				if (FoundClass)
				{
					UE_LOG(LogTemp, Warning, TEXT("лҹ°нғҖмһ„м—җм„ң BP_Aim лЎңл”© м„ұкіө!"));
					crosshairUI = CreateWidget<UUserWidget>(PC, FoundClass);
					if (crosshairUI)
					{
						crosshairUI->AddToViewport(1000);
						crosshairUI->SetVisibility(ESlateVisibility::Visible);
						UE_LOG(LogTemp, Warning, TEXT("лҹ°нғҖмһ„ BP_Aim UI мғқм„ұ м„ұкіө!"));
					}
				}
				else
				{
					UE_LOG(LogTemp, Error, TEXT("лҹ°нғҖмһ„м—җм„ңлҸ„ BP_Aimмқ„ м°ҫмқ„ мҲҳ м—ҶмҠөлӢҲлӢӨ."));
					UE_LOG(LogTemp, Error, TEXT("Content Browserм—җм„ң BP_Aimмқҳ м •нҷ•н•ң кІҪлЎңлҘј нҷ•мқён•ҳм„ёмҡ”."));
				}
			}
		}
		else
		{
			UE_LOG(LogTemp, Warning, TEXT("PlayerControllerлҘј м°ҫмқ„ мҲҳ м—ҶмқҢ"));
		}
	}, 0.1f, false);

}

// Called every frame
void ACharacterBase::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

}

// Called to bind functionality to input
void ACharacterBase::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
	if (auto* EIC = Cast<UEnhancedInputComponent>(PlayerInputComponent))
	{
		if (InputProxy) InputProxy->SetupPlayerBindings(EIC);
	}

}

//л‘җлҮҢ 2к°ңмӨ‘ л¬ҙм—Үмқ„ м„ нғқн•  кІғмқёк°Җ? 
void ACharacterBase::RefreshBrainActivation()
{
	
}

void ACharacterBase::InitActionsFromLoadout()
{
	if (!ActionComponent || !ActionLoadOutDA) return;
	
	for (const FActionSlot& Slot : ActionLoadOutDA->Actions)
	{
		UActionBase* Action = NewObject<UActionBase>(ActionComponent, Slot.ActionClass);

		FString NameString = Action->GetFName().ToString();
		UE_LOG(LogTemp, Warning, TEXT(" Name: %s"), *this->GetFName().ToString());

		UE_LOG(LogTemp, Warning, TEXT("Action Name: %s"), *NameString);
		
		Action->SetActionMontage(Slot.Montage);
		
		if (Slot.CooldownSec > 0.f)
		{
			Action->SetCooldown(Slot.CooldownSec);
		}
		
		ActionComponent->Register(Slot.ActionTag,Action); // л§ӨлӢҲм Җм—җ л“ұлЎқ(мҰү к·ё мәҗлҰӯн„°к°Җ н•  мҲҳ мһҲлҠ” м•Ўм…ҳ(м җн”„,мҠӨнӮ¬,л°ңмӮ¬ л“ұ)мқ„ мқҪм–ҙм„ң л“ұлЎқн•ҙмӨҖлӢӨ.
	}
}

void ACharacterBase::InitStatsFromDA()//м¶”нӣ„ мӣҖм§Ғмһ„ кҙҖл Ё мҠӨн…ҹ м¶”к°Җ
{
	if (ActionStatDA)
	{
		ActionStatComp->InitFromDa(ActionStatDA);
	}
}

void ACharacterBase::InitActionRouterMapFromDa()
{
	if (ActonRouterDA)
	{
		ActionRouter->InitFromRouterDA(ActonRouterDA);
	}
	;
}

void ACharacterBase::PlayActionMontage(UAnimMontage* montage)
{
	if (!montage)
	{
		return;
	}

	if (bIsDead && montage != DeathMontage)
	{
		return;
	}

	if (UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance())
	{
		AnimInstance->Montage_Play(montage);
	}
}


void ACharacterBase::PossessedBy(AController* NewController)
{
	Super::PossessedBy(NewController);
	if (InputProxy)
	{
		InputProxy->RegisterIMCToLocalPlayer(Cast<APlayerController>(NewController));
	}
}

void ACharacterBase::OnRep_Controller()
{
	Super::OnRep_Controller();
	if (InputProxy)
	{
		InputProxy->RegisterIMCToLocalPlayer(Cast<APlayerController>(GetController()));
	}
}

void ACharacterBase::ExitWallMode()
{
	GetCharacterMovement()->GravityScale = 1.0f;
	ActionStatComp->SetInWall(false);
	SetWallClimbMode(false);
    
	GEngine->AddOnScreenDebugMessage(-1, 3, FColor::Green, "Wall climb exited");
}

bool ACharacterBase::GetIsRunning()
{
	return bIsRunningMode;
}

void ACharacterBase::SetIsRunning(bool setRunMode)
{
	bIsRunningMode = setRunMode;
}

// лІҪ л¶ҷкё° лӘЁл“ң м„Өм • (л©”мқё н•ЁмҲҳ)
void ACharacterBase::SetWallClimbMode(bool bInWall)
{
	bIsInWallMode = bInWall;
	
	if (bInWall)
	{
		UE_LOG(LogTemp, Warning, TEXT("лІҪ л¶ҷкё° лӘЁл“ң нҷңм„ұнҷ” - м№ҙл©”лқј нҡҢм „л§Ң н—Ҳмҡ©"));
		EnableCameraRotationOnly();
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("лІҪ л¶ҷкё° лӘЁл“ң л№„нҷңм„ұнҷ” - мқјл°ҳ нҡҢм „ ліөк·Җ"));
		DisableCameraRotationOnly();
	}
}

// м№ҙл©”лқј нҡҢм „л§Ң н—Ҳмҡ© (л©”мӢңлҠ” кі м •)
void ACharacterBase::EnableCameraRotationOnly()
{
	if (!bIsInWallMode) return;
	
	UCharacterMovementComponent* MovementComp = GetCharacterMovement();
	if (MovementComp)
	{
		bOriginalOrientRotationToMovement = MovementComp->bOrientRotationToMovement;
		// мәҗлҰӯн„°к°Җ мқҙлҸҷ л°©н–ҘмңјлЎң нҡҢм „н•ҳлҠ” кІғмқ„ л№„нҷңм„ұнҷ”
		//MovementComp->bOrientRotationToMovement = false;
		// мәҗлҰӯн„° м „мІҙ нҡҢм „лҸ„ л№„нҷңм„ұнҷ”
		MovementComp->bUseControllerDesiredRotation = false;
	}

	// Pawnмқҳ нҡҢм „мқ„ л№„нҷңм„ұнҷ” (л©”мӢңк°Җ л”°лқј нҡҢм „н•ҳм§Җ м•ҠлҸ„лЎқ)
	bUseControllerRotationYaw = false;
	bUseControllerRotationPitch = false;
	bUseControllerRotationRoll = false;
	
	// л©”мӢң нҡҢм „мқ„ нҳ„мһ¬ мғҒнғңлЎң мҷ„м „нһҲ кі м •
	if (GetMesh())
	{
		// л©”мӢңмқҳ нҳ„мһ¬ нҡҢм „к°’ м ҖмһҘ
		OriginalMeshRotation = GetMesh()->GetComponentRotation();
		// л©”мӢңк°Җ л¶ҖлӘЁ(Pawn)мқҳ нҡҢм „мқ„ л”°лқјк°Җм§Җ м•ҠлҸ„лЎқ м„Өм •
		GetMesh()->SetAbsolute(false, true, false); // Location, Rotation, Scale
		// лҳҗлҠ” лҚ” нҷ•мӢӨн•ҳкІҢ н•ҳл Өл©ҙ:
		GetMesh()->SetWorldRotation(OriginalMeshRotation);
	}
	
	UE_LOG(LogTemp, Warning, TEXT("м№ҙл©”лқј нҡҢм „л§Ң н—Ҳмҡ© лӘЁл“ң м„Өм • мҷ„лЈҢ"));

}

// мқјл°ҳ нҡҢм „ лӘЁл“ңлЎң ліөк·Җ
void ACharacterBase::DisableCameraRotationOnly()
{
	// Movement Component м„Өм • ліөкө¬
	UCharacterMovementComponent* MovementComp = GetCharacterMovement();
	if (MovementComp)
	{
		bOriginalOrientRotationToMovement = MovementComp->bOrientRotationToMovement;
		MovementComp->bOrientRotationToMovement = true;
		MovementComp->bUseControllerDesiredRotation = true;
	}

	bUseControllerRotationYaw = true;
	bUseControllerRotationPitch = true;
	bUseControllerRotationRoll = true;
	
	// л©”мӢң нҡҢм „мқ„ нҳ„мһ¬ мғҒнғңлЎң мҷ„м „нһҲ кі м •
	if (GetMesh())
	{
		// л©”мӢңмқҳ нҳ„мһ¬ нҡҢм „к°’ м ҖмһҘ
		OriginalMeshRotation = GetMesh()->GetComponentRotation();
		// л©”мӢңк°Җ л¶ҖлӘЁ(Pawn)мқҳ нҡҢм „мқ„ л”°лқјк°Җм§Җ м•ҠлҸ„лЎқ м„Өм •
		GetMesh()->SetAbsolute(false, false, false); // Location, Rotation, Scale
		GetMesh()->SetWorldRotation(OriginalMeshRotation);
	}
	UE_LOG(LogTemp, Warning, TEXT("м№ҙл©”лқј нҡҢм „ лӘЁл“ң н•ҙм ң"));

}
//н”јкІ©	
void ACharacterBase::TakeDamage(float Amount, AActor* Causer)
{
	if (bIsDead)
	{
		return;
	}

	if (ActionStatComp)
	{
		if (DamagedMontage)
		{
			PlayActionMontage(DamagedMontage);
		}
		ActionStatComp->ApplyDamage(Amount, Causer);
		if (Brain-> CehckPlayerMode())
		{
			OnDamaged.Broadcast(ActionStatComp->CalculateHpPercentage());
		}
		
	}
}
//лҰ¬мҠӨнҸ°
void ACharacterBase::HandleDeath(AActor* DeadActor, AActor* KillerActor)
{
	// мәҗлҰӯн„°мқҳ мӣҖм§Ғмһ„ мҠӨнҶұ
	if (UCharacterMovementComponent* MovementComp = GetCharacterMovement())
	{
		MovementComp->StopMovementImmediately();
		MovementComp->SetMovementMode(MOVE_None);
	}

	GetWorldTimerManager().ClearTimer(RespawnTimerHandle);

	bIsDead = true;
	bRespawnRequested = false;

	const float PostDeathRespawnDelay = 4.0f;
	float FallbackRespawnDelay = PostDeathRespawnDelay;
	if (DeathMontage)
	{
		if (UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance())
		{
			AnimInstance->Montage_Stop(0.1f);
			const float PlayResult = AnimInstance->Montage_Play(DeathMontage);
			if (PlayResult > 0.f)
			{
				FOnMontageEnded MontageEndedDelegate;
				MontageEndedDelegate.BindUObject(this, &ACharacterBase::HandleDeathMontageEnded);
				AnimInstance->Montage_SetEndDelegate(MontageEndedDelegate, DeathMontage);
				FallbackRespawnDelay = FMath::Max(FallbackRespawnDelay, PlayResult + PostDeathRespawnDelay);
			}
		}
	}

	GetWorldTimerManager().SetTimer(RespawnTimerHandle, this, &ACharacterBase::RequestRespawn, FallbackRespawnDelay, false);

	// м „нҲ¬ л§ӨлӢҲм Җм—җ нӮ¬ мқҙлІӨнҠё м•ҢлҰј
	if (UWorld* World = GetWorld())
	{
		for (TActorIterator<ABattleManager> It(World); It; ++It)
		{
			ABattleManager* BM = *It;
			if (BM)
			{
				// Resolve killer character from projectile/ability ownership chain
				ACharacterBase* KillerChar = Cast<ACharacterBase>(KillerActor);
				if (!KillerChar && KillerActor)
				{
					// Try instigator first
					if (APawn* InstPawn = KillerActor->GetInstigator())
					{
						KillerChar = Cast<ACharacterBase>(InstPawn);
					}
					// Walk owner chain
					if (!KillerChar)
					{
						AActor* OwnerPtr = KillerActor->GetOwner();
						while (OwnerPtr && !KillerChar)
						{
							KillerChar = Cast<ACharacterBase>(OwnerPtr);
							OwnerPtr = OwnerPtr ? OwnerPtr->GetOwner() : nullptr;
						}
					}
				}
				BM->OnCharacterKilled(KillerChar, this);
				break;
			}
		}
	}
}



void ACharacterBase::HandleDeathMontageEnded(UAnimMontage* Montage, bool bInterrupted)
{
	if (Montage != DeathMontage)
	{
		return;
	}

	if (USkeletalMeshComponent* MeshComp = GetMesh())
	{
		if (UAnimInstance* AnimInstance = MeshComp->GetAnimInstance())
		{
			if (FOnMontageEnded* EndedDelegate = AnimInstance->Montage_GetEndedDelegate(DeathMontage))
			{
				EndedDelegate->Unbind();
			}
		}
	}

	GetWorldTimerManager().ClearTimer(RespawnTimerHandle);
	// лӘҪнғҖмЈј мў…лЈҢ 4мҙҲ л’Ө лҰ¬мҠӨнҸ° мҡ”мІӯ
	GetWorldTimerManager().SetTimer(RespawnTimerHandle, this, &ACharacterBase::RequestRespawn, 4.0f, false);
}

void ACharacterBase::RequestRespawn()
{
	if (bRespawnRequested)
	{
		GetWorldTimerManager().ClearTimer(RespawnTimerHandle);
		return;
	}

	bRespawnRequested = true;

	if (USkeletalMeshComponent* MeshComp = GetMesh())
	{
		if (UAnimInstance* AnimInstance = MeshComp->GetAnimInstance())
		{
			if (DeathMontage && AnimInstance->Montage_IsPlaying(DeathMontage))
			{
				AnimInstance->Montage_Stop(0.1f, DeathMontage);
			}
			if (FOnMontageEnded* EndedDelegate = AnimInstance->Montage_GetEndedDelegate(DeathMontage))
			{
				EndedDelegate->Unbind();
			}
		}
	}

	bIsDead = false;
	// кІҢмһ„ лӘЁл“ңлҘј к°Җм ёмҷҖ лҰ¬мҠӨнҸ° 
	if (AGameModeBase* GameMode = GetWorld()->GetAuthGameMode())
	{
		if (AInfinityFightersGameModeBase* IFGameMode = Cast<AInfinityFightersGameModeBase>(GameMode))
		{
			IFGameMode->RequestPlayerRespawn(GetController());
		}
	}
	// лҰ¬мҠӨнҸ° нғҖмқҙлЁёлҘј мҙҲкё°нҷ”
	GetWorldTimerManager().ClearTimer(RespawnTimerHandle);
}

void ACharacterBase::SetupAimEnemyWidget()
{
	if (!AimEnemyWidget || !AimEnemyWidgetClass)
	{
		UE_LOG(LogTemp, Warning, TEXT("AimEnemyWidget лҳҗлҠ” AimEnemyWidgetClassк°Җ nullмһ…лӢҲлӢӨ"));
		return;
	}

	// мң„м Ҝ нҒҙлһҳмҠӨ м„Өм •
	AimEnemyWidget->SetWidgetClass(AimEnemyWidgetClass);

	// мң„м Ҝ м„Өм •
	AimEnemyWidget->SetWidgetSpace(EWidgetSpace::Screen); // н•ӯмғҒ нҷ”л©ҙмқ„ н–Ҙн•Ё
	AimEnemyWidget->SetWorldScale3D(FVector(0.3f)); // мҡ”мІӯлҗң мҠӨмјҖмқј
	AimEnemyWidget->SetRelativeLocation(FVector(0.0f, 0.0f, 100.0f)); // мәҗлҰӯн„° лЁёлҰ¬ мң„

	// DrawSize м„Өм • (мң„м Ҝ нҒ¬кё°)
	AimEnemyWidget->SetDrawSize(FVector2D(200.0f, 100.0f));

	UE_LOG(LogTemp, Log, TEXT("AimEnemy мң„м Ҝ м„Өм • мҷ„лЈҢ: %s"), *GetName());
}

void ACharacterBase::ShowAimEnemyWidget(bool bShow)
{
	if (AimEnemyWidget)
	{
		AimEnemyWidget->SetVisibility(bShow);
		// лЎңк·ёлҘј л„Ҳл¬ҙ мһҗмЈј м¶ңл Ҙн•ҳм§Җ м•ҠлҸ„лЎқ мЎ°кұҙл¶ҖлЎң ліҖкІҪ
		/*if (bShow)
		{
			UE_LOG(LogTemp, Log, TEXT("AimEnemy мң„м Ҝ н‘ңмӢң: %s"), *GetName());
		}*/
	}
}

void ACharacterBase::UpdateAimEnemyWidgetVisibility()
{
	// AI мәҗлҰӯн„°к°Җ м•„лӢҲл©ҙ мІҳлҰ¬н•ҳм§Җ м•ҠмқҢ
	if (!Brain || Brain->Mode != EBrainMode::AI)
	{
		return;
	}

	// к°ҖмһҘ к°Җк№Ңмҡҙ н”Ңл Ҳмқҙм–ҙ мәҗлҰӯн„° м°ҫкё°
	ACharacterBase* NearestPlayer = GetNearestPlayerCharacter();
	if (!NearestPlayer)
	{
		ShowAimEnemyWidget(false);
		return;
	}

	// н”Ңл Ҳмқҙм–ҙ мӢңм•јк°Ғ лІ”мң„м—җ мһҲлҠ”м§Җ нҷ•мқё
	bool bInFieldOfView = IsInPlayerFieldOfView(NearestPlayer);
	ShowAimEnemyWidget(bInFieldOfView);
}

bool ACharacterBase::IsInPlayerFieldOfView(ACharacterBase* PlayerCharacter) const
{
	if (!PlayerCharacter || !PlayerCharacter->Camera)
	{
		return false;
	}

	FVector PlayerLocation = PlayerCharacter->GetActorLocation();
	FVector EnemyLocation = GetActorLocation();
	FVector PlayerForward = PlayerCharacter->Camera->GetForwardVector();

	// кұ°лҰ¬ мІҙнҒ¬
	float Distance = FVector::Dist(PlayerLocation, EnemyLocation);
	if (Distance > MaxDetectionRange)
	{
		return false;
	}

	// н”Ңл Ҳмқҙм–ҙм—җм„ң м ҒмңјлЎңмқҳ л°©н–Ҙ лІЎн„°
	FVector DirectionToEnemy = (EnemyLocation - PlayerLocation).GetSafeNormal();

	// мӢңм•јк°Ғ мІҙнҒ¬
	float DotProduct = FVector::DotProduct(PlayerForward, DirectionToEnemy);
	float AngleInRadians = FMath::Acos(DotProduct);
	float AngleInDegrees = FMath::RadiansToDegrees(AngleInRadians);

	// мӢңм•јк°Ғ лІ”мң„ лӮҙм—җ мһҲлҠ”м§Җ нҷ•мқё
	bool bInAngle = AngleInDegrees <= (FieldOfViewAngle * 0.5f);

	if (!bInAngle)
	{
		return false;
	}

	// мһҘм• л¬ј мІҙнҒ¬ (Line Trace)
	FHitResult HitResult;
	FCollisionQueryParams CollisionParams;
	CollisionParams.AddIgnoredActor(PlayerCharacter);
	CollisionParams.AddIgnoredActor(const_cast<ACharacterBase*>(this));

	// н”Ңл Ҳмқҙм–ҙмқҳ лҲҲ лҶ’мқҙм—җм„ң м Ғмқҳ мӨ‘мӢ¬мңјлЎң л ҲмқҙмәҗмҠӨнҠё
	FVector TraceStart = PlayerLocation + FVector(0, 0, 80); // н”Ңл Ҳмқҙм–ҙ лҲҲ лҶ’мқҙ
	FVector TraceEnd = EnemyLocation + FVector(0, 0, 50);    // м Ғ мӨ‘мӢ¬

	bool bHit = GetWorld()->LineTraceSingleByChannel(
		HitResult,
		TraceStart,
		TraceEnd,
		ECC_Visibility,
		CollisionParams
	);

	// нһҲнҠёк°Җ м—Ҷмңјл©ҙ мӢңм•јм—җ ліҙмһ„, нһҲнҠёк°Җ мһҲмңјл©ҙ мһҘм• л¬јм—җ к°Җл Өм§җ
	return !bHit;
}

ACharacterBase* ACharacterBase::GetNearestPlayerCharacter() const
{
	ACharacterBase* NearestPlayer = nullptr;
	float MinDistance = MaxDetectionRange;

	// мӣ”л“ңмқҳ лӘЁл“  CharacterBase кІҖмғү
	for (TActorIterator<ACharacterBase> ActorItr(GetWorld()); ActorItr; ++ActorItr)
	{
		ACharacterBase* Character = *ActorItr;

		// мһҗкё° мһҗмӢ мқҖ м ңмҷё
		if (!Character || Character == this)
		{
			continue;
		}

		// AIк°Җ м•„лӢҢ мәҗлҰӯн„°(н”Ңл Ҳмқҙм–ҙ)л§Ң кІҖмғү
		UCBrainComponent* BrainComp = Character->FindComponentByClass<UCBrainComponent>();
		if (!BrainComp || BrainComp->Mode == EBrainMode::AI)
		{
			continue;
		}

		// кұ°лҰ¬ кі„мӮ°
		float Distance = FVector::Dist(GetActorLocation(), Character->GetActorLocation());
		if (Distance < MinDistance)
		{
			MinDistance = Distance;
			NearestPlayer = Character;
		}
	}

	return NearestPlayer;
}
